apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argo-apps/mcm
    repoURL: 'git@github.com:VerodaClient/upgrade-testing.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
