{{ if and .Values.mgmtcluster (eq .Values.mgmtcluster.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: tigera-manager-mcm
  namespace: tigera-manager
spec:
  type: LoadBalancer
  ports:
    - port: 9449
      protocol: TCP
      targetPort: 9449
  selector:
    k8s-app: tigera-manager
{{ end }}
