apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJkR2xuWlhKaEszUnBaMlZ5WVY5cGJuUmxjbTVoYkRwWlRVNDFNRXMxUVV4VFJqaExNVUpHVjBjeFZEQklTVWhDVTBOU1dEQkJUamt5VHpKSU5VRkZRVlZUUXpaQk5sWkJOa3BGUVUxRVRsVmFORlZXUXpSSiIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9Cgo=
kind: Secret
metadata:
  name: tigera-pull-secret
  namespace: tigera-operator
type: kubernetes.io/dockerconfigjson
