apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-enterprise-managed-1
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    name: ce-mngd
    namespace: tigera-operator
  source:
    path: tigera-operator-ent
    repoURL: 'git@github.com:VerodaClient/mcm-testing.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.mngd.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 35
      backoff:
        duration: 30s
        factor: 1
        maxDuration: 3m
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: beats.beat.k8s.elastic.co
      jsonPointers:
        - /spec

