apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-custom-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'git@github.com:VerodaClient/upgrade-testing.git'
    path: environments
    targetRevision: HEAD
  destination:
    name: ce-mgmt
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Replace=true
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 35
      backoff:
        duration: 30s
        factor: 1
        maxDuration: 3m
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: beats.beat.k8s.elastic.co
      jsonPointers:
        - /spec
