apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-custom-configs 
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: ce-mgmt
  project: default
  source:
    path: environments
    repoURL: 'git@github.com:VerodaClient/charts.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.dev.yaml
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 35
      backoff:
        duration: 30s
        factor: 1
        maxDuration: 3m
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: beats.beat.k8s.elastic.co
      jsonPointers:
        - /spec

